### ISSUE TITLE
Indirects are not implemented for Group or Digital IO

### ISSUE THREAD

**Issue by connoralbright** [onerobotics/tp_plus#11]
Example of desired usage:
`DestinationRegister = R[1]`
`SourceGroupInputNumber = R[2]`
`DestinationRegister = indirect('GroupInput', SourceGroupInputNumber)`

Robot code equivalent:
`R[1:DestinationRegister] = GI[ R[2:SourceGroupInputNumber] ]`

Indirects that are supported currently (taken directly from `indirect_node.rb`):
- position
- position_register
- flag
- timer
- user_alarm
- user_frame

**Comment by unreal** [comment]
Fixed, but this changes the API.... TP+ no longer checks for a valid string for the first argument of `indirect` and simply returns what you specify to upper-case.

e.g. indirect('timer', 1) => TIMER[1], indirect('p',2) => P[2], indirect('uframe',5) => UFRAME[5]
