### ISSUE TITLE
Multiple Position Registers cannot be added together at once. 

### ISSUE THREAD

**Issue by connoralbright** [onerobotics/tp_plus#12]
It seems that more than two position registers cannot be added together at once. A program doing this will compile in TP+ just fine, but fail on loading into the controller. I get the error:
`Error loading program F_Example'
'The ASCII to binary translation may have failed. Check this controller's error log for more details`
The alarm history only says the line number and column of where the error occurred. 
Only adding two Position Registers together at time lets the program load correctly. 

Note that it seems possible to add more than two Position Registers together working within the robot controller, you just cant import code that does that. 

`PosRegA = PR[1]`
`PosRegB = PR[2]`
`PosRegC = PR[3]`
`PosRegCombined = PR[4]`

Non-working example:
`PosRegCombined = PosRegA + PosRegB + PosRegC`

What does work:
`PosRegCombined = PosRegA + PosRegB`
`PosRegCombined = PosRegCombined + PosRegC`

**Comment by unreal** [comment]
Does TP+ produce a mixed logic expression? E.g. PR[4]=(PR[1]+PR[2]+PR[3])
or does it fail to include the parens? I'm not sure if either is actually
valid on the controller... Might have to put a special check in to produce
what you mentioned.

**Comment by connoralbright** [comment]
Interesting...
`.ls` output from TP+ (with variable names removed):
` : PR[4]=(PR[1]+PR[2]+PR[3]) ;`
If I remove the parens from the `.ls` the file loads successfully into the controller.

**Comment by unreal** [comment]
One might argue this is an issue with FANUC's type checker ;)

Should be easy enough to handle this special case. I prefer x=a+b+c vs
x=a+b; x=x+c
