### ISSUE TITLE
can_be_inlined? not implemented for node set_skip_node

### ISSUE THREAD

**Issue by connoralbright** [onerobotics/tp_plus#13]
possible code would probably look something like:
```
def can_be_inlined?
    true
end
```
Not really sure if that should be True or False.
I need to figure out how to start working from source on my end...

**Comment by unreal** [comment]
`can_be_inlined?` is used for generating `IF (...),...`-style expressions. Generally only program calls , jumps (obviously), and some expressions can be done this way.

In retrospect, all of the nodes should probably inherit from some `BaseNode` with `can_be_inlined?` defined as false.
