### ISSUE TITLE
Parens need to be used for many cases of outputs

### ISSUE THREAD

**Issue by connoralbright** [onerobotics/tp_plus#15]
Invalid:
`DO[19:Vaccum_Status]=RO[1:Vaccum] ;`
Valid:
`DO[19:Vaccum_Status]=(RO[1:Vaccum]) ;`

This seems to be true for most types of outputs when not using `On`, `Off`, `Pulse`, or `R[n]`.

In `io_node.rb`, this line seems relevant:
`        options[:force_parens] ? "(#{s})" : s`

As a workaround, in TP+, manually placing the parens in the .tpp code works:
`Vaccum_Status = (Vaccum)`

**Comment by unreal** [comment]
hmm, one might argue this is another one of those cases that should be fixed in TP ;)

TP+'s type-checking and handling of parens/mixed-logic is pretty bad and needs major work.
