### ISSUE TITLE
Readme Example Error

### ISSUE THREAD

**Issue by jdexyz** [onerobotics/tp_plus#19]
When I run the readme example on a fresh install, I get an `Parse error on line 18 column 30: "mm" (WORD)` error.
The line is also highlighted when I paste it in `http://tp-plus.herokuapp.com/translate`
I believe the problem lies in the speed definition.

```
foo  := R[1]
bar  := DO[1]
baz  := DO[2]

home := PR[1]
lpos := PR[2]

foo = 1

@loop
  foo += 1

  jump_to @loop if foo < 10

turn_on bar if foo == 5
toggle baz

linear_move.to(home).at(2000mm/s).term(0)
get_linear_position(lpos)
```

Thank you for this very convenient tool !

**Comment by jdexyz** [comment]
Ok, the `test` directory expained everything.
The correct syntax is simply `linear_move.to(home).at(2000, 'mm/s').term(0)`.
Will submit a PR.

**Comment by unreal** [comment]
Thanks for the PR!

The documentation is admittedly sorely lacking, but yes, please check the tests for all supported functionality.

FWIW I have not been actively developing TP+ for years. I did use it to develop one production system years ago, but I have not used it recently. There are probably a million things I would change about it if I were to pick it up again, but I am working on other things. Feel free to try it out. More PRs welcome :)
